sudo: false
os: power
dist: xenial

language: go

go:
- 1.8.x

go_import_path: github.com/prometheus/prometheus

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then make check_license style test; fi
- if [ "$TRAVIS_OS_NAME" == "power" ]; then make all; fi
